import SwiftUI
import SwiftData

// MARK: - Shopping List View
struct ShoppingListView: View {
    @Environment(\.modelContext) private var modelContext
    @Query(sort: \ShoppingListItem.addedDate, order: .reverse) var items: [ShoppingListItem]
    @Query(sort: \DietPlan.createdAt, order: .reverse) var plans: [DietPlan]

    @State private var showAddItem = false
    @State private var showGenerateFromPlan = false
    @State private var showShareSheet = false
    @State private var showClearAllAlert = false
    @State private var searchText = ""

    private var unpurchasedItems: [ShoppingListItem] {
        items.filter { !$0.isPurchased }
    }

    private var purchasedItems: [ShoppingListItem] {
        items.filter { $0.isPurchased }
    }

    private var filteredUnpurchased: [ShoppingListItem] {
        if searchText.isEmpty {
            return unpurchasedItems
        }
        return unpurchasedItems.filter { $0.name.localizedCaseInsensitiveContains(searchText) }
    }

    private var groupedItems: [(category: IngredientCategory, items: [ShoppingListItem])] {
        let grouped = Dictionary(grouping: filteredUnpurchased) { $0.category }
        return IngredientCategory.allCases.compactMap { category in
            guard let items = grouped[category], !items.isEmpty else { return nil }
            return (category, items)
        }
    }

    private var shareListText: String {
        var text = "🛒 Shopping List\n\n"

        for group in groupedItems {
            text += "── \(group.category.rawValue) ──\n"
            for item in group.items {
                let checkbox = item.isPurchased ? "☑️" : "☐"
                let quantity = item.quantity.isEmpty ? "" : " (\(item.quantity))"
                text += "\(checkbox) \(item.name)\(quantity)\n"
            }
            text += "\n"
        }

        text += "Generated by DietAI"
        return text
    }

    var body: some View {
        NavigationStack {
            Group {
                if items.isEmpty {
                    emptyState
                } else {
                    shoppingList
                }
            }
            .navigationTitle("Shopping List")
            .searchable(text: $searchText, prompt: "Search items")
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    if !unpurchasedItems.isEmpty {
                        ShareLink(item: shareListText) {
                            Image(systemName: "square.and.arrow.up")
                        }
                    }
                }

                ToolbarItem(placement: .topBarTrailing) {
                    Menu {
                        Button(action: { showAddItem = true }) {
                            Label("Add Item", systemImage: "plus")
                        }
                        Button(action: { showGenerateFromPlan = true }) {
                            Label("Generate from Plan", systemImage: "wand.and.stars")
                        }
                        if !items.isEmpty {
                            Divider()
                            if !purchasedItems.isEmpty {
                                Button(role: .destructive, action: clearPurchased) {
                                    Label("Clear Purchased", systemImage: "checkmark.circle")
                                }
                            }
                            Button(role: .destructive, action: { showClearAllAlert = true }) {
                                Label("Clear All", systemImage: "trash")
                            }
                        }
                    } label: {
                        Image(systemName: "plus.circle.fill")
                            .font(.title2)
                    }
                }
            }
            .sheet(isPresented: $showAddItem) {
                AddShoppingItemView()
            }
            .sheet(isPresented: $showGenerateFromPlan) {
                if let plan = plans.first {
                    GenerateShoppingListView(plan: plan)
                }
            }
            .alert("Clear Shopping List", isPresented: $showClearAllAlert) {
                Button("Cancel", role: .cancel) { }
                Button("Clear All", role: .destructive) {
                    clearAll()
                }
            } message: {
                Text("Are you sure you want to remove all \(items.count) items from your shopping list? This cannot be undone.")
            }
        }
    }

    // MARK: - Empty State
    private var emptyState: some View {
        ContentUnavailableView {
            Label("No Shopping Items", systemImage: "cart")
        } description: {
            Text("Add items manually or generate a list from your meal plan")
        } actions: {
            HStack {
                Button("Add Item") {
                    showAddItem = true
                }
                .buttonStyle(.bordered)

                if plans.first != nil {
                    Button("Generate from Plan") {
                        showGenerateFromPlan = true
                    }
                    .buttonStyle(.borderedProminent)
                }
            }
        }
    }

    // MARK: - Shopping List
    private var shoppingList: some View {
        List {
            // Summary card
            Section {
                ShoppingListSummaryCard(
                    totalItems: unpurchasedItems.count,
                    purchasedItems: purchasedItems.count,
                    estimatedTotal: unpurchasedItems.compactMap { $0.estimatedPrice }.reduce(0, +)
                )
                .listRowInsets(EdgeInsets())
                .listRowBackground(Color.clear)
            }

            // Unpurchased items grouped by category
            ForEach(groupedItems, id: \.category) { group in
                Section {
                    ForEach(group.items) { item in
                        ShoppingItemRow(item: item) {
                            togglePurchased(item)
                        }
                    }
                    .onDelete { indexSet in
                        deleteItems(group.items, at: indexSet)
                    }
                } header: {
                    HStack {
                        Image(systemName: group.category.icon)
                        Text(group.category.rawValue)
                    }
                }
            }

            // Purchased items
            if !purchasedItems.isEmpty {
                Section {
                    ForEach(purchasedItems) { item in
                        ShoppingItemRow(item: item) {
                            togglePurchased(item)
                        }
                    }
                    .onDelete { indexSet in
                        deleteItems(purchasedItems, at: indexSet)
                    }
                } header: {
                    HStack {
                        Text("Purchased")
                        Spacer()
                        Button("Clear All", role: .destructive) {
                            clearPurchased()
                        }
                        .font(.caption)
                    }
                }
            }
        }
    }

    // MARK: - Actions
    private func togglePurchased(_ item: ShoppingListItem) {
        withAnimation {
            item.isPurchased.toggle()
        }
        try? modelContext.save()
    }

    private func deleteItems(_ items: [ShoppingListItem], at offsets: IndexSet) {
        for index in offsets {
            modelContext.delete(items[index])
        }
    }

    private func clearPurchased() {
        for item in purchasedItems {
            modelContext.delete(item)
        }
    }

    private func clearAll() {
        for item in items {
            modelContext.delete(item)
        }
    }
}

// MARK: - Shopping List Summary Card
struct ShoppingListSummaryCard: View {
    let totalItems: Int
    let purchasedItems: Int
    let estimatedTotal: Double

    private var progress: Double {
        guard totalItems + purchasedItems > 0 else { return 0 }
        return Double(purchasedItems) / Double(totalItems + purchasedItems)
    }

    var body: some View {
        VStack(spacing: 12) {
            HStack {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Shopping Progress")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                    HStack(alignment: .firstTextBaseline, spacing: 4) {
                        Text("\(purchasedItems)")
                            .font(.system(size: 32, weight: .bold, design: .rounded))
                        Text("/ \(totalItems + purchasedItems) items")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                    }
                }

                Spacer()

                ZStack {
                    Circle()
                        .stroke(Color.gray.opacity(0.2), lineWidth: 8)
                    Circle()
                        .trim(from: 0, to: progress)
                        .stroke(Color.green, style: StrokeStyle(lineWidth: 8, lineCap: .round))
                        .rotationEffect(.degrees(-90))
                    Text("\(Int(progress * 100))%")
                        .font(.caption)
                        .fontWeight(.semibold)
                }
                .frame(width: 60, height: 60)
            }

            if estimatedTotal > 0 {
                HStack {
                    Image(systemName: "dollarsign.circle")
                        .foregroundStyle(.green)
                    Text("Estimated total:")
                    Spacer()
                    Text(String(format: "$%.2f", estimatedTotal))
                        .fontWeight(.semibold)
                }
                .font(.subheadline)
            }
        }
        .padding()
        .background(Color(uiColor: .secondarySystemGroupedBackground))
        .cornerRadius(16)
        .padding(.horizontal)
    }
}

// MARK: - Shopping Item Row
struct ShoppingItemRow: View {
    @Bindable var item: ShoppingListItem
    let onToggle: () -> Void

    var body: some View {
        HStack(spacing: 12) {
            Button(action: onToggle) {
                Image(systemName: item.isPurchased ? "checkmark.circle.fill" : "circle")
                    .font(.title2)
                    .foregroundStyle(item.isPurchased ? .green : .secondary)
            }
            .buttonStyle(.plain)

            VStack(alignment: .leading, spacing: 2) {
                Text(item.name)
                    .strikethrough(item.isPurchased)
                    .foregroundStyle(item.isPurchased ? .secondary : .primary)

                if !item.quantity.isEmpty {
                    Text(item.quantity)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            Spacer()

            if let price = item.estimatedPrice, price > 0 {
                Text(String(format: "$%.2f", price))
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }
}

// MARK: - Add Shopping Item View
struct AddShoppingItemView: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss

    @State private var name = ""
    @State private var quantity = ""
    @State private var category: IngredientCategory = .other
    @State private var estimatedPrice = ""

    var body: some View {
        NavigationStack {
            Form {
                Section("Item Details") {
                    TextField("Item name", text: $name)

                    TextField("Quantity (e.g., 1 lb, 2 cans)", text: $quantity)

                    Picker("Category", selection: $category) {
                        ForEach(IngredientCategory.allCases, id: \.self) { cat in
                            Label(cat.rawValue, systemImage: cat.icon).tag(cat)
                        }
                    }
                }

                Section("Optional") {
                    HStack {
                        Text("Estimated Price")
                        Spacer()
                        TextField("0.00", text: $estimatedPrice)
                            .keyboardType(.decimalPad)
                            .multilineTextAlignment(.trailing)
                            .frame(width: 80)
                        Text("$")
                            .foregroundStyle(.secondary)
                    }
                }
            }
            .navigationTitle("Add Item")
            .navigationBarTitleDisplayMode(.inline)
            .formKeyboardDismissible()
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Add") {
                        addItem()
                        dismiss()
                    }
                    .disabled(name.isEmpty)
                }
            }
        }
    }

    private func addItem() {
        let item = ShoppingListItem(
            name: name,
            quantity: quantity,
            category: category,
            estimatedPrice: Double(estimatedPrice)
        )
        modelContext.insert(item)
        try? modelContext.save()
    }
}

// MARK: - Meal Time Point (for range comparison)
struct MealTimePoint: Comparable {
    let date: Date
    let mealType: MealType

    static func < (lhs: MealTimePoint, rhs: MealTimePoint) -> Bool {
        if Calendar.current.isDate(lhs.date, inSameDayAs: rhs.date) {
            return lhs.mealType.sortOrder < rhs.mealType.sortOrder
        }
        return lhs.date < rhs.date
    }
}

// MARK: - Generate Shopping List View
struct GenerateShoppingListView: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss

    let plan: DietPlan

    @State private var startDate: Date
    @State private var startMeal: MealType = .breakfast
    @State private var endDate: Date
    @State private var endMeal: MealType = .dinner
    @State private var ingredients: [IngredientItem] = []
    @State private var isAggregating = false
    @State private var useSmartGrouping = true

    private let aggregator = IngredientAggregator.shared

    // Map weekday to plan day (plans repeat weekly)
    private func planDay(for weekday: Int) -> DailyPlan? {
        // weekday: 1=Sunday, 2=Monday, ... 7=Saturday
        let calendar = Calendar.current
        return plan.days.first { day in
            calendar.component(.weekday, from: day.date) == weekday
        }
    }

    // Get meals in the selected range (accounting for weekly repetition)
    private var mealsInRange: [(date: Date, meal: Meal)] {
        let calendar = Calendar.current
        var results: [(date: Date, meal: Meal)] = []

        // Iterate through each day in the date range
        var currentDate = calendar.startOfDay(for: startDate)
        let endDateDay = calendar.startOfDay(for: endDate)

        while currentDate <= endDateDay {
            let weekday = calendar.component(.weekday, from: currentDate)

            if let dayPlan = planDay(for: weekday) {
                for meal in dayPlan.meals {
                    let point = MealTimePoint(date: currentDate, mealType: meal.type)
                    let startPoint = MealTimePoint(date: startDate, mealType: startMeal)
                    let endPoint = MealTimePoint(date: endDate, mealType: endMeal)

                    if point >= startPoint && point <= endPoint {
                        results.append((date: currentDate, meal: meal))
                    }
                }
            }

            currentDate = calendar.date(byAdding: .day, value: 1, to: currentDate) ?? currentDate
        }

        return results
    }

    private var mealCount: Int {
        mealsInRange.count
    }

    private var dayCount: Int {
        let calendar = Calendar.current
        let start = calendar.startOfDay(for: startDate)
        let end = calendar.startOfDay(for: endDate)
        return (calendar.dateComponents([.day], from: start, to: end).day ?? 0) + 1
    }

    private var isValidRange: Bool {
        let startPoint = MealTimePoint(date: startDate, mealType: startMeal)
        let endPoint = MealTimePoint(date: endDate, mealType: endMeal)
        return startPoint <= endPoint
    }

    init(plan: DietPlan) {
        self.plan = plan
        // Set default dates based on plan
        let sortedDays = plan.days.sorted { $0.date < $1.date }
        let firstDate = sortedDays.first?.date ?? Date()
        let lastDate = sortedDays.last?.date ?? Date()
        _startDate = State(initialValue: firstDate)
        _endDate = State(initialValue: lastDate)
    }

    var body: some View {
        NavigationStack {
            Form {
                // Date Range Selection
                Section {
                    VStack(alignment: .leading, spacing: 16) {
                        // FROM
                        VStack(alignment: .leading, spacing: 8) {
                            Text("FROM")
                                .font(.caption)
                                .fontWeight(.semibold)
                                .foregroundStyle(.secondary)

                            HStack {
                                DatePicker(
                                    "",
                                    selection: $startDate,
                                    displayedComponents: .date
                                )
                                .labelsHidden()

                                Picker("", selection: $startMeal) {
                                    ForEach(MealType.allCases, id: \.self) { type in
                                        Text(type.rawValue).tag(type)
                                    }
                                }
                                .pickerStyle(.menu)
                                .tint(.primary)
                            }
                        }

                        Divider()

                        // TO
                        VStack(alignment: .leading, spacing: 8) {
                            Text("TO")
                                .font(.caption)
                                .fontWeight(.semibold)
                                .foregroundStyle(.secondary)

                            HStack {
                                DatePicker(
                                    "",
                                    selection: $endDate,
                                    displayedComponents: .date
                                )
                                .labelsHidden()

                                Picker("", selection: $endMeal) {
                                    ForEach(MealType.allCases, id: \.self) { type in
                                        Text(type.rawValue).tag(type)
                                    }
                                }
                                .pickerStyle(.menu)
                                .tint(.primary)
                            }
                        }
                    }
                    .padding(.vertical, 4)
                } header: {
                    Text("Date Range")
                }

                // Summary
                Section {
                    HStack {
                        Image(systemName: "calendar")
                            .foregroundStyle(.blue)
                        if isValidRange {
                            Text("\(mealCount) meals over \(dayCount) day\(dayCount == 1 ? "" : "s")")
                        } else {
                            Text("Invalid range")
                                .foregroundStyle(.red)
                        }
                        Spacer()
                    }
                }

                // Smart Grouping Option
                Section {
                    Toggle(isOn: $useSmartGrouping) {
                        HStack {
                            Image(systemName: "sparkles")
                                .foregroundStyle(.purple)
                            VStack(alignment: .leading, spacing: 2) {
                                Text("Smart Grouping")
                                Text("Uses AI to combine similar ingredients")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }
                    .tint(.purple)
                }

                // Ingredients Preview
                if !ingredients.isEmpty {
                    Section("Ingredients to Add (\(ingredients.count))") {
                        ForEach(ingredients, id: \.name) { ingredient in
                            HStack {
                                VStack(alignment: .leading, spacing: 2) {
                                    Text(ingredient.name.capitalized)
                                    if !ingredient.quantity.isEmpty {
                                        Text(ingredient.quantity)
                                            .font(.caption)
                                            .foregroundStyle(.secondary)
                                    }
                                }
                                Spacer()
                                Text("\(ingredient.count) meal\(ingredient.count > 1 ? "s" : "")")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }
                }
            }
            .navigationTitle("Generate List")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    if isAggregating {
                        ProgressView()
                            .progressViewStyle(.circular)
                    } else {
                        Button(ingredients.isEmpty ? "Preview" : "Add \(ingredients.count) Items") {
                            if ingredients.isEmpty {
                                Task { await generatePreview() }
                            } else {
                                addToShoppingList()
                                dismiss()
                            }
                        }
                        .disabled(!isValidRange || mealCount == 0)
                    }
                }
            }
            .onChange(of: startDate) { _, _ in ingredients = [] }
            .onChange(of: startMeal) { _, _ in ingredients = [] }
            .onChange(of: endDate) { _, _ in ingredients = [] }
            .onChange(of: endMeal) { _, _ in ingredients = [] }
            .onChange(of: useSmartGrouping) { _, _ in ingredients = [] }
        }
    }

    private func generatePreview() async {
        isAggregating = true

        // Collect all ingredients from meals in range
        var allIngredients: [MealIngredient] = []
        for (_, meal) in mealsInRange {
            allIngredients.append(contentsOf: meal.ingredients)
        }

        if useSmartGrouping {
            // Use smart aggregator with AI
            let results = await aggregator.aggregate(
                ingredients: allIngredients,
                useAI: ModelManager.shared.isModelLoaded
            )

            ingredients = results.map { result in
                IngredientItem(
                    name: result.canonicalName,
                    quantity: result.aggregatedQuantity.displayString,
                    count: result.aggregatedQuantity.totalCount
                )
            }
        } else {
            // Use simple aggregation (original behavior)
            var aggregated: [String: SimpleAggregatedIngredient] = [:]

            for ingredient in allIngredients {
                let key = ingredient.name.lowercased()

                if var existing = aggregated[key] {
                    existing.quantities.append(ingredient.quantity)
                    existing.count += 1
                    aggregated[key] = existing
                } else {
                    aggregated[key] = SimpleAggregatedIngredient(
                        baseName: ingredient.name,
                        quantities: [ingredient.quantity],
                        count: 1
                    )
                }
            }

            ingredients = aggregated.values.map { agg in
                let quantityStr = combineQuantities(agg.quantities)
                return IngredientItem(
                    name: agg.baseName,
                    quantity: quantityStr,
                    count: agg.count
                )
            }
            .sorted { $0.name.lowercased() < $1.name.lowercased() }
        }

        isAggregating = false
    }

    /// Combine multiple quantities into a readable string
    private func combineQuantities(_ quantities: [String]) -> String {
        let nonEmpty = quantities.filter { !$0.isEmpty }
        if nonEmpty.isEmpty {
            return ""
        }

        // Group same quantities
        var counts: [String: Int] = [:]
        for q in nonEmpty {
            counts[q, default: 0] += 1
        }

        // Format: "2x 1/2 cup, 3x 1 tbsp" or just "1/2 cup" if single
        if counts.count == 1, let (qty, count) = counts.first {
            return count > 1 ? "\(count)x \(qty)" : qty
        }

        return counts.map { qty, count in
            count > 1 ? "\(count)x \(qty)" : qty
        }.sorted().joined(separator: ", ")
    }

    private func addToShoppingList() {
        for ingredient in ingredients {
            let item = ShoppingListItem(
                name: ingredient.name.capitalized,
                quantity: ingredient.quantity,
                category: categorize(ingredient.name)
            )
            modelContext.insert(item)
        }
        try? modelContext.save()
    }

    private func categorize(_ ingredient: String) -> IngredientCategory {
        let lower = ingredient.lowercased()

        // Simple categorization based on common keywords
        let proteins = ["chicken", "beef", "pork", "fish", "salmon", "tuna", "shrimp", "tofu", "egg", "turkey"]
        let dairy = ["milk", "cheese", "yogurt", "butter", "cream"]
        let vegetables = ["lettuce", "tomato", "onion", "garlic", "carrot", "broccoli", "spinach", "pepper", "cucumber", "celery"]
        let fruits = ["apple", "banana", "orange", "berry", "grape", "mango", "avocado", "lemon", "lime"]
        let grains = ["rice", "pasta", "bread", "oat", "quinoa", "flour", "cereal"]
        let spices = ["salt", "pepper", "cumin", "paprika", "oregano", "basil", "cinnamon"]

        if proteins.contains(where: { lower.contains($0) }) { return .protein }
        if dairy.contains(where: { lower.contains($0) }) { return .dairy }
        if vegetables.contains(where: { lower.contains($0) }) { return .vegetables }
        if fruits.contains(where: { lower.contains($0) }) { return .fruits }
        if grains.contains(where: { lower.contains($0) }) { return .grains }
        if spices.contains(where: { lower.contains($0) }) { return .spices }

        return .other
    }
}

struct IngredientItem {
    let name: String
    let quantity: String
    let count: Int
}

struct SimpleAggregatedIngredient {
    let baseName: String
    var quantities: [String]
    var count: Int
}
